<?
$PERM["rew"]["9"]="W";
$PERM["/"]["*"]="R";
$PERM[".idea"]["2"]="D";
$PERM[".idea"]["3"]="D";
$PERM[".idea"]["4"]="D";
$PERM[".idea"]["5"]="D";
$PERM[".idea"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
?>